package com.lx.dataObject;

public class UserPasswordDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.id
     *
     * @mbggenerated Sun Nov 15 09:44:12 GMT+08:00 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.encrpy_password
     *
     * @mbggenerated Sun Nov 15 09:44:12 GMT+08:00 2020
     */
    private String encrpyPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.user_id
     *
     * @mbggenerated Sun Nov 15 09:44:12 GMT+08:00 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.id
     *
     * @return the value of user_password.id
     *
     * @mbggenerated Sun Nov 15 09:44:12 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.id
     *
     * @param id the value for user_password.id
     *
     * @mbggenerated Sun Nov 15 09:44:12 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.encrpy_password
     *
     * @return the value of user_password.encrpy_password
     *
     * @mbggenerated Sun Nov 15 09:44:12 GMT+08:00 2020
     */
    public String getEncrpyPassword() {
        return encrpyPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.encrpy_password
     *
     * @param encrpyPassword the value for user_password.encrpy_password
     *
     * @mbggenerated Sun Nov 15 09:44:12 GMT+08:00 2020
     */
    public void setEncrpyPassword(String encrpyPassword) {
        this.encrpyPassword = encrpyPassword == null ? null : encrpyPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.user_id
     *
     * @return the value of user_password.user_id
     *
     * @mbggenerated Sun Nov 15 09:44:12 GMT+08:00 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.user_id
     *
     * @param userId the value for user_password.user_id
     *
     * @mbggenerated Sun Nov 15 09:44:12 GMT+08:00 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}